name: Push To Windows VM

# Controls when the workflow will run
on:
  # Triggers the workflow on pushj request events for the main branch
  push:
    branches: [main]

jobs:
  deploys:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2
      - name: Copy to host directory
        run: powershell Copy-Item -Path C:\Users\corey\actions-runner\_work\CICD Lab\* -Destination C:\inetpub\wwwroot -force
